name: Aveva Assignment 01 Deployment to Azure

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy-to-ACR:
    runs-on: ubuntu-latest
    outputs:
      hash: ${{ steps.vars.outputs.hash }}
    steps:
    - id: checkout
      name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'

    - name: Install Yarn
      run: corepack enable yarn
      
    - name: Build
      run: yarn build

    - name: Configure Azure ACR
      uses: azure/docker-login@v2
      with:
        login-server: ${{ vars.AZ_CR_SERVER }}
        username: ${{ secrets.GHA_USERNAME }}
        password: ${{ secrets.GHA_PASSWORD }}

    - name: Getting commit hash
      id: vars
      run: echo "::set-output name=hash::$(git rev-parse --short ${{ github.sha }})"

    - name: Build and push Docker image to ACR
      env:
        ACR_REGISTRY: ${{ vars.AZ_CR_SERVER }}
        APP_NAME: ${{ github.repository.name }}
        IMAGE_TAG: ${{ steps.vars.outputs.hash }}
      run: |
        docker build -f blog-starter.Dockerfile -t $ACR_REGISTRY/$APP_NAME:$IMAGE_TAG -t $ACR_REGISTRY/$APP_NAME:latest .
        docker push $ACR_REGISTRY/$APP_NAME --all-tags

  deploy-to-container:
    runs-on: ubuntu-latest
    needs: build-and-deploy-to-ACR

    steps:
    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.GHA_CREDENTIALS }}

    - name: Deploy to Azure Web App
      uses: azure/container-apps-deploy-action@v1
      env:
        IMAGE_TAG: ${{ needs.build-and-deploy-to-ACR.outputs.hash }}
        ACR_SERVER: ${{ vars.AZ_CR_SERVER }}
        APP_NAME: ${{ github.repository.name }}
      with:
        registryUrl: $ACR_SERVER
        imageToDeploy: $ACR_SERVER/$APP_NAME:$IMAGE_TAG
        targetPort: 3000
        ingress: external
        containerAppName: $APP_NAME-app-dev
        containerAppEnvironment: $APP_NAME-environment-dev
        resourceGroup: $APP_NAME