name: IaC Terraform Deployment

on:
  push:
    paths:
      - 'iac/** .github/workflows/terraform-deploy.yaml'
    branches:
      - master

jobs:
  iac-terraform-deployment:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.GHA_USERNAME }}
      ARM_CLIENT_SECRET: ${{ secrets.GHA_PASSWORD }}
      ARM_SUBSCRIPTION_ID: ${{ vars.AZ_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ vars.AZ_TENANT_ID }}
      TF_VERSION: 1.10.5

    steps:
    - id: checkout
      name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.GHA_CREDENTIALS }}

    - name: Getting repository name
      id: repo
      run: echo "::set-output name=name::$(echo ${{ github.repository }} | cut -d'/' -f2)"

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: $TF_VERSION

    - name: Run Terraform Init
      run: terraform init
      working-directory: ./iac/

    - name: Run Terraform Validate
      run: terraform validate
      working-directory: ./iac/

    - name: Run Terraform Plan
      run: terraform plan -var "application_name=${{ steps.repo.outputs.name }}" -var "subscription_id=${{ vars.AZ_SUBSCRIPTION_ID }}" -var "env_id=dev" -out=tfplan
      working-directory: ./iac/

    - name: Run Terraform Apply
      run: terraform apply -auto-approve tfplan
      working-directory: ./iac/

    - name: Notify Failure
      if: failure()
      run: echo "Terraform deployment failed ${{ github.ref_name }}"